# Generated by Django 5.2.4 on 2025-08-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="nickname",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_onboarding",
            field=models.BooleanField(default=False),
        ),
    ]
