# Generated by Django 5.2.4 on 2025-08-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_userselloinginfo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertype",
            name="description",
            field=models.TextField(
                blank=True, default="설명이 없습니다.", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="usertype",
            name="seloing_type",
            field=models.CharField(
                choices=[
                    ("혼돈의 달변가형", "Begginer"),
                    ("성장중인 소통 초보형", "Elementary"),
                    ("신중한 전략가형", "Intermediate"),
                    ("소통의 장인형", "Advanced"),
                    ("마스터 커뮤니케이터", "Master"),
                ],
                max_length=30,
            ),
        ),
    ]
