# Generated by Django 5.2.4 on 2025-08-13 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usertype_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userselloinginfo',
            name='level',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.usertype'),
        ),
    ]
