# Generated by Django 5.2.4 on 2025-09-08 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_blacklistedtoken_refreshtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_step', models.CharField(choices=[('goal', '목표'), ('job', '직업'), ('interest', '흥미'), ('completed', '완료')], default='goal', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OnboardingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(choices=[('ai', 'AI'), ('user', '사용자')], max_length=10)),
                ('content', models.TextField()),
                ('step', models.CharField(choices=[('goal', '목표'), ('job', '직업'), ('interest', '흥미'), ('completed', '완료')], max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.onboardingsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
