# Generated by Django 5.2.4 on 2025-08-07 05:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("global_exp", models.IntegerField(default=0)),
                ("global_candy", models.IntegerField(default=0)),
                (
                    "global_record_time",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                ("global_attendance_count", models.IntegerField(default=0)),
                ("global_seloing_count", models.IntegerField(default=0)),
                ("global_seloing_score", models.IntegerField(default=0)),
                ("global_seloing_score_avg", models.FloatField(default=0.0)),
                ("global_repeat_score", models.IntegerField(default=0)),
                ("global_stable_score", models.IntegerField(default=0)),
                ("global_topic_score", models.IntegerField(default=0)),
                ("global_filler_score", models.IntegerField(default=0)),
                ("global_repeat_count", models.IntegerField(default=0)),
                ("global_filler_count", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_exp", models.IntegerField(default=0)),
                ("total_candy", models.IntegerField(default=0)),
                (
                    "total_record_time",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                ("total_attendance_count", models.IntegerField(default=0)),
                ("total_seloing_count", models.IntegerField(default=0)),
                ("total_seloing_score", models.IntegerField(default=0)),
                ("total_seloing_score_avg", models.FloatField(default=0.0)),
                ("total_repeat_score", models.IntegerField(default=0)),
                ("total_stable_score", models.IntegerField(default=0)),
                ("total_topic_score", models.IntegerField(default=0)),
                ("total_filler_score", models.IntegerField(default=0)),
                ("total_repeat_count", models.IntegerField(default=0)),
                ("total_filler_count", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
