# Generated by Django 5.2.4 on 2025-08-07 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Seloing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("selected_topic", models.CharField(max_length=200)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SeloingAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_transcript", models.TextField()),
                ("analyzed_transcript", models.TextField()),
                ("disfluency_feedback", models.TextField()),
                ("topic_feedback", models.TextField()),
                ("stability_feedback", models.TextField()),
                (
                    "seloing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seloing.seloing",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SeloingAudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=255)),
                ("file_url", models.URLField()),
                ("duration_seconds", models.FloatField()),
                (
                    "seloing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seloing.seloing",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SeloingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_score", models.IntegerField()),
                ("repeat_score", models.IntegerField()),
                ("topic_score", models.IntegerField()),
                ("filler_score", models.IntegerField()),
                ("stability_score", models.IntegerField()),
                ("repeat_count", models.IntegerField()),
                ("filler_count", models.IntegerField()),
                (
                    "seloing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seloing.seloing",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SeloingReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("earned_exp", models.IntegerField()),
                ("earned_candy", models.IntegerField()),
                (
                    "seloing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seloing.seloing",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
