# Generated by Django 5.2.4 on 2025-08-14 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seloing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic1', models.CharField(max_length=300)),
                ('topic2', models.CharField(max_length=300)),
                ('topic3', models.CharField(max_length=300)),
                ('is_select', models.CharField(choices=[('none', '선택안함'), ('1', '첫번째 주제'), ('2', '두번째 주제'), ('3', '세번째 주제'), ('skip', '다시뽑기')], default='none', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
